[project]
name = "myprojectllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=3.34.0",
]
